Show test summary in Github Comment (#877)

diff --git a/.github/workflows/acceptance-test.yml b/.github/workflows/acceptance-test.yml
--- a/.github/workflows/acceptance-test.yml
+++ b/.github/workflows/acceptance-test.yml
@@ -119,7 +119,9 @@ jobs:
         continue-on-error: true
 
       - name: Acceptance test cases
+        id: test-execution
         run: |
+              echo "tests_executed=tests_execution_not_successful" >> $GITHUB_OUTPUT
               args="${{ github.event.client_payload.slash_command.args }}"
               providers=(${args})
               index=0
@@ -174,56 +176,91 @@ jobs:
               # Ensure log file exists
               if [ ! -f test_output.log ]; then
                   echo "Error: test_output.log not found!"
-                  exit 0  # Ignore missing file instead of failing
+                  exit 1  # Ignore missing file instead of failing
               fi
 
               # Extract total test cases executed safely
-              TOTAL_RUN=$(grep -c '^=== RUN' test_output.log || echo 0)
-              TOTAL_PASSED=$(grep -c '^--- PASS' test_output.log || echo 0)
-              TOTAL_FAILED=$(grep -c '^--- FAIL' test_output.log || echo 0)
-              TOTAL_SKIPPED=$(grep -c '^--- SKIP' test_output.log || echo 0)
+              TOTAL_RUN=$(grep -c '^=== RUN' test_output.log)
+              if [ "$TOTAL_RUN" -eq 0 ]; then
+                  echo "No test cases executed. Exiting..."
+                  exit 1
+              fi
+
+              # Extract counts of passed, failed, and skipped tests
+              TOTAL_PASSED=$(grep -c '^--- PASS' test_output.log)
+              TOTAL_FAILED=$(grep -c '^--- FAIL' test_output.log)
+              TOTAL_SKIPPED=$(grep -c '^--- SKIP' test_output.log)
+
+              # Set output as successful for GitHub Actions which will be used in subsequent steps, Set only if tests were executed
+              echo "tests_executed=tests_execution_successful" >> $GITHUB_OUTPUT
 
               # Calculate percentages safely
+              PASS_PERCENT=0
+              FAIL_PERCENT=0
+              SKIP_PERCENT=0
               if [ "$TOTAL_RUN" -gt 0 ]; then
-                  PASS_PERCENT=$((TOTAL_PASSED * 100 / TOTAL_RUN))
-                  FAIL_PERCENT=$((TOTAL_FAILED * 100 / TOTAL_RUN))
-                  SKIP_PERCENT=$((TOTAL_SKIPPED * 100 / TOTAL_RUN))
-              else
-                  PASS_PERCENT=0
-                  FAIL_PERCENT=0
-                  SKIP_PERCENT=0
+                  if [ "$TOTAL_PASSED" -gt 0 ]; then
+                      PASS_PERCENT=$((TOTAL_PASSED * 100 / TOTAL_RUN))
+                  fi
+                  if [ "$TOTAL_FAILED" -gt 0 ]; then
+                      FAIL_PERCENT=$((TOTAL_FAILED * 100 / TOTAL_RUN))
+                  fi
+                  if [ "$TOTAL_SKIPPED" -gt 0 ]; then
+                      SKIP_PERCENT=$((TOTAL_SKIPPED * 100 / TOTAL_RUN))
+                  fi
               fi
 
-              echo "==================================================🧪 TEST SUMMARY 🧪================================================================================="
-              echo "Total Test Cases Run 🐹🚀: $TOTAL_RUN"
-              echo "Total Test Cases Passed 🐹✅: $TOTAL_PASSED ($PASS_PERCENT %)" 
-              echo "Total Test Cases Failed 🐹❌: $TOTAL_FAILED ($FAIL_PERCENT %)"
-              echo "Total Test Cases Skipped 🐹⚠️: $TOTAL_SKIPPED ($SKIP_PERCENT %)"
-              echo "=================================================================================================================================================="
+              # Write summary to a file
+              {
+                echo "==================================================🧪 TEST SUMMARY 🧪================================================================================="
+                echo "Total Test Cases Run 🚀: $TOTAL_RUN"
+                echo "Total Test Cases Passed ✅: $TOTAL_PASSED ($PASS_PERCENT %)" 
+                echo "Total Test Cases Failed ❌: $TOTAL_FAILED ($FAIL_PERCENT %)"
+                echo "Total Test Cases Skipped ⚠️: $TOTAL_SKIPPED ($SKIP_PERCENT %)"
+                echo "=================================================================================================================================================="
+                echo ""
+                echo "================================================== TESTS SUCCEEDED ✅ ============================================================================="
+                if [ "$TOTAL_PASSED" -gt 0 ]; then
+                    echo ""
+                    grep '^--- PASS' test_output.log | awk '{print "✅ " $3}' || true
+                else
+                    echo ""
+                    echo "No tests passed 😞❗"
+                fi
+                echo "==================================================================================================================================================="
+                echo ""
+                echo "================================================== TESTS FAILED ❌ ================================================================================"
+                if [ "$TOTAL_FAILED" -gt 0 ]; then
+                    echo ""
+                    grep '^--- FAIL' test_output.log | awk '{print "❌ " $3}' || true
+                else
+                    echo "🎉💃 No tests failed 🕺🎉"
+                fi
+                echo "==================================================================================================================================================="
+                echo ""
+                echo "================================================== TESTS SKIPPED ⚠️ =============================================================================="
+                if [ "$TOTAL_SKIPPED" -gt 0 ]; then
+                    awk '
+                      /^=== RUN/ { testname=$3; reason="No reason provided" }
+                      /--- SKIP/ { print "⚠️ " testname "   : Reason: ➡️ :  " reason }
+                      /^[[:space:]]+/ { reason=$0 }' test_output.log || true
+                else
+                    echo "🎉💃 No tests skipped 🕺🎉"
+                fi
+                echo "==================================================================================================================================================="
+                echo ""
 
-              echo "================================================== TESTS SUCCEEDED ✅ ============================================================================="
-              if [ "$TOTAL_PASSED" -gt 0 ]; then
-                  echo ""
-                  grep '^--- PASS' test_output.log | awk '{print "✅ " $3}' || true
-              fi
+              } > test_summary.txt
+              echo "TEST_SUMMARY_FILE=test_summary.txt" >> $GITHUB_ENV
 
-              echo "==================================================================================================================================================="
-              echo "================================================== TESTS FAILED ❌ ================================================================================"
-              if [ "$TOTAL_FAILED" -gt 0 ]; then
-                  echo ""
-                  grep '^--- FAIL' test_output.log | awk '{print "❌ " $3}' || true
-              fi
+              # Write to GitHub output for PR comment
+              {
+                echo "summary_content<<EOF"
+                cat test_summary.txt
+                echo "EOF"
+              } >> "$GITHUB_OUTPUT"
 
-              echo "==================================================================================================================================================="
-              echo "================================================== TESTS SKIPPED ⚠️ =============================================================================="
-              if [ "$TOTAL_SKIPPED" -gt 0 ]; then
-                  awk '
-                    /^=== RUN/ { testname=$3; reason="No reason provided" }
-                    /--- SKIP/ { print "⚠️ " testname "   : Reason: ➡️ :  " reason }
-                    /^[[:space:]]+/ { reason=$0 }' test_output.log || true
-              fi
 
-              echo "==================================================================================================================================================="
               if [ "$TOTAL_FAILED" -gt 0 ]; then
                   echo ""
                   echo "================== FAILURE DETAILS OF TESTCASES EXECUTED ==============================================================================================="
@@ -233,6 +270,7 @@ jobs:
                           echo "========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 ======================================================================================="
                           awk "/=== RUN   $test/,/--- FAIL: $test/" test_output.log | sed 's/^/    /' || true
                           echo "==========================================================================================================================================================="
+                          echo ""
                       fi
                   done
               fi
@@ -245,10 +283,10 @@ jobs:
               else
                   exit 0
               fi
-        continue-on-error: true
 
+      # Code Coverage Check only if tests executed successfully
       - name: Code Coverage Check
-        if: ${{ always() }}
+        if: ${{ steps.test-execution.outputs.tests_executed == 'tests_execution_successful' }}
         run:  |
               echo "Code coverage: Checking if code coverage is above threshold..."
               export TESTCOV_THRESHOLD=50
@@ -262,24 +300,38 @@ jobs:
                   echo "CODE_COVERAGE_OUTPUT=Current line coverage ($totalCoverage) is below threshold ($TESTCOV_THRESHOLD). Kindly add more acceptance tests." >> $GITHUB_ENV
                   echo "Current coverage ($totalCoverage) is below threshold ($TESTCOV_THRESHOLD)."
               fi
-
-      # Update the comment back
-      - name: Update comment
-        uses: peter-evans/create-or-update-comment@v1
-        if: ${{ always() }}
+      
+      # Post build status along with test summary as a comment only if tests executed successfully
+      - name: Post build status and test summary
+        if: ${{ steps.test-execution.outputs.tests_executed == 'tests_execution_successful' }}
+        uses: peter-evans/create-or-update-comment@v4
         with:
           comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
           body: |
-            ```
-            Acceptance test run status: ${{ job.status }}
-            **📌 [View GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})**
-            ${{ env.CODE_COVERAGE_OUTPUT }}
-
+            - 🧪 **`Build Status: `** `${{ job.status }}`
+            - 📌 **`GitHub Action: `[View GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})`
+            - 📊 **`Code Coverage: `** `${{ env.CODE_COVERAGE_OUTPUT }}`
+            - 📝 **`Test Summary: `**
+            ```txt
+            ${{ steps.test-execution.outputs.summary_content }}
             ```
           reaction-type: hooray
+      
+      # Post only Build Status and workflow info as Comment if tests execution is not successful
+      - name: Post build status and workflow info
+        if: ${{ steps.test-execution.outputs.tests_executed == 'tests_execution_not_successful' || !steps.test-execution.outputs.tests_executed }}
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
+          body: |
+            - 🧪 **`Build Status: `** `${{ job.status }}`
+            - 📌 **`GitHub Action: `** [View GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
+            - ℹ️ **`Tests were not successfully executed, so no summary is available.`**
+
+          reaction-type: confused
 
       # Print job status
-      - name: Print job status
+      - name: Workflow Status
         if: ${{ always() }}
         run: |
           STATUS="${{ job.status }}"
