modify pipeline

diff --git a/.github/workflows/acceptance-test.yml b/.github/workflows/acceptance-test.yml
--- a/.github/workflows/acceptance-test.yml
+++ b/.github/workflows/acceptance-test.yml
@@ -8,9 +8,19 @@ jobs:
     runs-on: self-hosted
     if: github.event_name == 'repository_dispatch'
     steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+      - name: Trigger Event
+        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
+
+      - name: Runner Info
+        run: echo "🐧 This job is now running on runner: $RUNNER_NAME (OS: ${{ runner.os }})"
+
+      - name: Pull Request Info
+        run: |
+          echo "your repository is ${{ github.repository }}."
+          echo "PR Number: ${{ github.event.client_payload.pull_request.number }}"
+          echo "PR Title: ${{ github.event.client_payload.pull_request.title }}"
+          echo "Branch Name: ${{ github.event.client_payload.pull_request.head.ref }}"
+
       - name: Check out repository code
         uses: actions/checkout@v4
         with:
@@ -228,8 +238,14 @@ jobs:
 
               echo "Tests Execution is done, please debug if any failures"
 
-              exit 0  # Force success exit
-              
+              # 🔁 This now ensures the stage fails if tests fail
+              if [ "$TOTAL_FAILED" -gt 0 ]; then
+                  exit 1
+              else
+                  exit 0
+              fi
+        continue-on-error: true
+
       - name: Code Coverage Check
         if: ${{ always() }}
         run:  |
@@ -253,43 +269,21 @@ jobs:
         with:
           comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
           body: |
-            > Acceptance test run status: ${{ job.status }}
-            > **📌 [View GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})**
-            > ${{ env.CODE_COVERAGE_OUTPUT }}
+            ```
+            Acceptance test run status: ${{ job.status }}
+            **📌 [View GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})**
+            ${{ env.CODE_COVERAGE_OUTPUT }}
+
+            ```
           reaction-type: hooray
 
-      # Update check run for Acceptance Test
-      - uses: actions/github-script@v5
-        id: update-check-run
+      # Print job status
+      - name: Print job status
         if: ${{ always() }}
-        env:
-          number: ${{ github.event.client_payload.pull_request.number }}
-          job: ${{ github.job }}
-          # Conveniently, job.status maps to https://developer.github.com/v3/checks/runs/#update-a-check-run
-          conclusion: ${{ job.status }} 
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const { data: pull } = await github.rest.pulls.get({
-              ...context.repo,
-              pull_number: process.env.number
-            });
-            const ref = pull.head.sha;
-            const { data: checks } = await github.rest.checks.listForRef({
-              ...context.repo,
-              ref
-            });
-            const check = checks.check_runs.filter(c => c.name === process.env.job);
-            if (check.length == 0) {
-              return "Check is not present, ignoring this step."
-            }
-            const { data: result } = await github.rest.checks.update({
-              ...context.repo,
-              check_run_id: check[0].id,
-              status: 'completed',
-              conclusion: process.env.conclusion
-            });
-            return result;
-
-      - run: echo "Build Done!!"
-      - run: echo "🍏 This job's status is ${{ job.status }}."
+        run: |
+          STATUS="${{ job.status }}"
+          if [ "$STATUS" == "failure" ]; then
+            echo "Job Status: $STATUS 😢"
+          else
+            echo "Job Status: $STATUS ✅"
+          fi
