Workflow update to run particular tests

diff --git a/.github/workflows/acceptance-test.yml b/.github/workflows/acceptance-test.yml
--- a/.github/workflows/acceptance-test.yml
+++ b/.github/workflows/acceptance-test.yml
@@ -20,7 +20,40 @@ jobs:
         with:
           go-version: 1.17
       - name: Acceptance test cases
-        run: ${{ secrets.ACCEPTANCE_TEST_ARGS }} make testacc
+        run: |
+              args="${{ github.event.client_payload.slash_command.args }}"
+              providers=(${args})
+              index=0
+              n=${#providers[@]}
+              runFlag=""
+              for provider in $args
+              do 
+                  if [ "$provider" = "foundation" ]
+                      then 
+                          runFlag+="TestAccFoundation*"
+                  elif [ "$provider" = "foundation_central" ]
+                      then
+                          runFlag+="TestAccFC*"
+                  elif [ "$provider" = "karbon" ]
+                      then
+                          runFlag+="TestAccKarbon*"
+                  elif [ "$provider" = "pc" ]
+                      then
+                          runFlag+="TestAccNutanix*"
+                  else 
+                          echo "Invalid provider=$provider given in arguments."
+                          exit 1
+                  fi
+                  if [ $index -lt $((n-1)) ]
+                      then
+                          runFlag+="|"
+                  fi
+                  index=$((index+1))
+              done
+              export TESTARGS='-run="'$runFlag'"'
+              echo "TESTARGS = $TESTARGS"
+              echo '${{ secrets.FOUNDATION_CONFIG }}' > test_foundation_config.json
+              ${{ secrets.ACCEPTANCE_TEST_ARGS }} make testacc
       - name: Code Coverage Check
         run:  |
               echo "Code coverage: Checking if code coverage is above threshold..."
